apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: secondary-reptile-nodejs 
  janus-idp.io/tekton: secondary-reptile-nodejs
  backstage.io/kubernetes-id: secondary-reptile-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e 
  app.kubernetes.io/part-of: secondary-reptile-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  