apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: secondary-reptile-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: secondary-reptile-nodejs 
  name: secondary-reptile-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: secondary-reptile-nodejs 
